//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodPressureForms.EmailSender {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmailSender.IEmailNotifications")]
    public interface IEmailNotifications {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailNotifications/notify", ReplyAction="http://tempuri.org/IEmailNotifications/notifyResponse")]
        void notify();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailNotifications/notify", ReplyAction="http://tempuri.org/IEmailNotifications/notifyResponse")]
        System.Threading.Tasks.Task notifyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailNotifications/SendNotification", ReplyAction="http://tempuri.org/IEmailNotifications/SendNotificationResponse")]
        void SendNotification(string messageBody, string toAddressString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailNotifications/SendNotification", ReplyAction="http://tempuri.org/IEmailNotifications/SendNotificationResponse")]
        System.Threading.Tasks.Task SendNotificationAsync(string messageBody, string toAddressString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmailNotificationsChannel : BloodPressureForms.EmailSender.IEmailNotifications, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmailNotificationsClient : System.ServiceModel.ClientBase<BloodPressureForms.EmailSender.IEmailNotifications>, BloodPressureForms.EmailSender.IEmailNotifications {
        
        public EmailNotificationsClient() {
        }
        
        public EmailNotificationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmailNotificationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailNotificationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailNotificationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void notify() {
            base.Channel.notify();
        }
        
        public System.Threading.Tasks.Task notifyAsync() {
            return base.Channel.notifyAsync();
        }
        
        public void SendNotification(string messageBody, string toAddressString) {
            base.Channel.SendNotification(messageBody, toAddressString);
        }
        
        public System.Threading.Tasks.Task SendNotificationAsync(string messageBody, string toAddressString) {
            return base.Channel.SendNotificationAsync(messageBody, toAddressString);
        }
    }
}
